### ISSUE TITLE
이미지 분류 서버 이미지 서버로 전환

### ISSUE THREAD

**Issue by ymym1024** [TeamCookCaps/ImageClassification#6]
### TODO

- [x] 이미지 크기 값 리턴하는 로직 추가
- [x] 이미지 메타데이터 가져오기
- [x] 반환 json data 생성
